import scrapy
import re
import json
import logging
import os
import time
from collections import defaultdict
from urllib.parse import urljoin
from ..gitstar_ranking.items import GitHubRepoItem
from scrapy.exceptions import CloseSpider

class GitHubReposSpider(scrapy.Spider):
    name = 'github_repos'
    allowed_domains = ['gitstar-ranking.com']
    base_url = 'https://gitstar-ranking.com/repositories'
    
    custom_settings = {
        'CONCURRENT_REQUESTS': 8,
        'DOWNLOAD_DELAY': 1,
        'RETRY_TIMES': 3,
        'ROBOTSTXT_OBEY': True,
        'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'LOG_LEVEL': 'INFO',
        'FEEDS': {
            'output/github_repos.json': {
                'format': 'json',
                'encoding': 'utf8',
                'store_empty': False,
                'overwrite': True,
            },
            'output/github_repos.csv': {
                'format': 'csv',
                'encoding': 'utf8',
                'store_empty': False,
                'overwrite': True,
            },
        },
        'AUTOTHROTTLE_ENABLED': True,
        'AUTOTHROTTLE_START_DELAY': 1.0,
        'AUTOTHROTTLE_MAX_DELAY': 3.0,
        'STATS_DUMP': True,  # Enable stats printing
    }
    
    def __init__(self, *args, **kwargs):
        super(GitHubReposSpider, self).__init__(*args, **kwargs)
        self.repo_count = 0
        self.max_repos = 5000
        self.logger.setLevel(logging.INFO)
        self.page_mapping = self._load_page_mapping()
        self.collected_repos = {}  # Store repos by rank
        self.start_time = time.time()
        self.last_progress_time = time.time()
        self.progress_interval = 10  # Show progress every 10 seconds
        
        # Worker management
        self.num_workers = self.custom_settings['CONCURRENT_REQUESTS']
        self.worker_stats = defaultdict(lambda: {'pages': 0, 'repos': 0, 'errors': 0, 'page_range': None})
        
        # Ensure output directory exists
        output_dir = os.path.join(os.getcwd(), 'output')
        if not os.path.exists(output_dir):
            os.makedirs(output_dir)
    
    def _load_page_mapping(self):
        """Load the page mapping generated by scout spider"""
        mapping = {}
        try:
            with open('page_mapping.txt', 'r') as f:
                for line in f:
                    page, count = map(int, line.strip().split(','))
                    mapping[page] = count
            self.logger.info(f"Loaded mapping for {len(mapping)} pages")
            return mapping
        except FileNotFoundError:
            self.logger.warning("No page mapping found. Run scout spider first!")
            return {}
    
    def start_requests(self):
        """Initialize workers with their assigned page ranges"""
        if not self.page_mapping:
            raise CloseSpider("No page mapping available. Please run scout spider first.")
        
        total_pages = len(self.page_mapping)
        pages_per_worker = total_pages // self.num_workers
        extra_pages = total_pages % self.num_workers
        
        self.logger.info(f"\nWorker Distribution Plan:"
                        f"\n- Total pages: {total_pages}"
                        f"\n- Number of workers: {self.num_workers}"
                        f"\n- Pages per worker: {pages_per_worker}"
                        f"\n- Extra pages: {extra_pages}")
        
        # Distribute pages among workers
        current_page = 1
        for worker_id in range(self.num_workers):
            # Calculate page range for this worker
            worker_pages = pages_per_worker + (1 if worker_id < extra_pages else 0)
            end_page = current_page + worker_pages - 1
            
            # Store worker's page range
            self.worker_stats[worker_id]['page_range'] = (current_page, end_page)
            
            # Generate requests for this worker's pages
            for page in range(current_page, end_page + 1):
                if page in self.page_mapping:
                    url = f"{self.base_url}?page={page}"
                    self.logger.debug(f"Assigning page {page} to Worker {worker_id}")
                    yield scrapy.Request(
                        url,
                        callback=self.parse,
                        errback=self.errback,
                        meta={
                            'worker_id': worker_id,
                            'page': page,
                            'start_idx': self._get_start_idx(page),
                            'end_idx': self._get_end_idx(page)
                        }
                    )
            
            current_page = end_page + 1
    
    def _get_start_idx(self, page):
        """Calculate starting repository index for a page"""
        start_idx = 1
        for p in range(1, page):
            if p in self.page_mapping:
                start_idx += self.page_mapping[p]
        return start_idx
    
    def _get_end_idx(self, page):
        """Calculate ending repository index for a page"""
        end_idx = self._get_start_idx(page) + self.page_mapping[page] - 1
        return min(end_idx, self.max_repos)
    
    def errback(self, failure):
        """Handle request errors"""
        self.logger.error(f"Request failed: {failure.value}")
        url_info = failure.request.meta.get('url_info')
        if url_info:
            # Update worker stats
            worker_id = id(failure.request)
            self.worker_stats[worker_id]['errors'] += 1
            
            # Retry failed requests with lower priority
            retries = failure.request.meta.get('retry_count', 0)
            if retries < 3:  # Max 3 retries
                self.logger.info(f"Retrying {url_info['url']}")
                yield scrapy.Request(
                    url_info['url'],
                    callback=self.parse,
                    errback=self.errback,
                    priority=url_info['priority'] - 100,  # Lower priority for retries
                    meta={
                        'url_info': url_info,
                        'retry_count': retries + 1
                    }
                )
    
    def parse(self, response):
        """Parse repository data with worker assignment"""
        worker_id = response.meta['worker_id']
        page = response.meta['page']
        start_idx = response.meta['start_idx']
        end_idx = response.meta['end_idx']
        
        # Update worker stats
        self.worker_stats[worker_id]['pages'] += 1
        
        repo_items = response.css('.list-group-item.paginated_item')
        current_idx = start_idx
        
        for item in repo_items:
            if current_idx > end_idx or self.repo_count >= self.max_repos:
                return
            
            repo = self._extract_repo_data(item, current_idx)
            if repo:
                self.collected_repos[repo['rank']] = repo
                self.repo_count += 1
                self.worker_stats[worker_id]['repos'] += 1
                yield repo
        
        # Show progress periodically
        current_time = time.time()
        if current_time - self.last_progress_time >= self.progress_interval:
            self._show_progress()
            self.last_progress_time = current_time
    
    def _show_progress(self):
        """Display current progress and worker statistics"""
        elapsed_time = time.time() - self.start_time
        repos_per_second = self.repo_count / elapsed_time if elapsed_time > 0 else 0
        
        # Calculate worker-specific metrics
        worker_metrics = {}
        for worker_id, stats in self.worker_stats.items():
            repos = stats['repos']
            pages = stats['pages']
            errors = stats['errors']
            avg_repos_per_page = repos / pages if pages > 0 else 0
            
            worker_metrics[worker_id] = {
                'repos': repos,
                'pages': pages,
                'errors': errors,
                'avg_repos_per_page': avg_repos_per_page
            }
        
        # Sort workers by number of repos processed
        sorted_workers = sorted(worker_metrics.items(), key=lambda x: x[1]['repos'], reverse=True)
        
        self.logger.info(
            f"\nProgress Update:"
            f"\n- Repositories collected: {self.repo_count}/{self.max_repos}"
            f"\n- Progress: {(self.repo_count/self.max_repos*100):.1f}%"
            f"\n- Elapsed time: {elapsed_time:.1f}s"
            f"\n- Overall speed: {repos_per_second:.1f} repos/second"
            f"\n- Active workers: {len(worker_metrics)}"
            f"\n\nWorker Statistics (sorted by repos processed):"
        )
        
        for worker_id, metrics in sorted_workers:
            self.logger.info(
                f"Worker {worker_id % 1000}:"
                f" Pages={metrics['pages']}"
                f" Repos={metrics['repos']}"
                f" Avg={metrics['avg_repos_per_page']:.1f} repos/page"
                f" Errors={metrics['errors']}"
            )
    
    def _extract_repo_data(self, item, current_idx):
        """Extract repository data from a list item"""
        repo = GitHubRepoItem()
        
        # Extract rank from the name span
        rank_text = item.css('.name::text').get()
        if rank_text:
            try:
                # Extract number before the dot (e.g., "49." -> 49)
                repo['rank'] = int(rank_text.strip().rstrip('.'))
            except (ValueError, AttributeError):
                self.logger.warning(f"Could not parse rank from: {rank_text}")
                return None
        else:
            self.logger.warning("No rank found in item")
            return None
        
        # Extract name
        full_name = item.css('.name .hidden-xs.hidden-sm::text').get()
        if not full_name:
            full_name = item.css('.name .hidden-md.hidden-lg::text').get()
        if full_name:
            repo['name'] = full_name.strip()
        else:
            href = item.css('a::attr(href)').get()
            if href and href.startswith('/'):
                repo['name'] = href.lstrip('/')
            else:
                return None
        
        # Extract stars
        stars_text = item.css('.stargazers_count::text').getall()
        if stars_text:
            # Get the last text node which contains the star count
            stars_text = stars_text[-1].strip()
            try:
                repo['stars'] = int(stars_text.replace(',', ''))
            except ValueError:
                self.logger.warning(f"Could not parse stars from: {stars_text}")
                repo['stars'] = 0
        else:
            repo['stars'] = 0
        
        # Extract description
        desc = item.css('.repo-description::attr(title)').get()
        if not desc:
            desc = item.css('.repo-description::text').get()
        repo['description'] = desc.strip() if desc else "No description available"
        
        # Extract language
        lang = item.css('.repo-language span::text').get()
        repo['language'] = lang.strip() if lang else "No language available"
        
        # Extract avatar URL - try multiple approaches
        avatar_url = None
        
        # 1. Try direct selector first
        avatar_url = item.css('img.avatar_image_big::attr(src)').get()
        if not avatar_url:
            # 2. Try getting the img element and its src attribute
            img_element = item.css('img.avatar_image_big')
            if img_element:
                avatar_url = img_element.attrib.get('src')
        
        if not avatar_url:
            # 3. Try alternate selectors
            avatar_url = item.css('.avatar_image_big::attr(src)').get()
            if not avatar_url:
                avatar_url = item.css('.list-group-item img::attr(src)').get()
        
        repo['avatar_url'] = avatar_url.strip() if avatar_url else None
        
        # Extract repo URL
        repo_url = item.css('a::attr(href)').get()
        if repo_url:
            repo['repo_url'] = urljoin('https://gitstar-ranking.com', repo_url)
        
        return repo
    
    def closed(self, reason):
        """Handle spider closure"""
        self._show_progress()  # Show final progress
        
        if self.repo_count < self.max_repos:
            self.logger.error(f"Only collected {self.repo_count} repositories out of {self.max_repos}")
        else:
            self.logger.info(f"Successfully collected {self.repo_count} repositories")
        
        # Verify collected data
        missing_ranks = []
        for rank in range(1, self.max_repos + 1):
            if rank not in self.collected_repos:
                missing_ranks.append(rank)
        
        if missing_ranks:
            self.logger.error(f"Missing repositories for ranks: {missing_ranks}")
        else:
            self.logger.info("All repository ranks collected successfully")
        
        # Calculate final worker statistics
        worker_metrics = {}
        total_pages = 0
        total_errors = 0
        
        for worker_id, stats in self.worker_stats.items():
            repos = stats['repos']
            pages = stats['pages']
            errors = stats['errors']
            avg_repos_per_page = repos / pages if pages > 0 else 0
            
            worker_metrics[worker_id] = {
                'repos': repos,
                'pages': pages,
                'errors': errors,
                'avg_repos_per_page': avg_repos_per_page
            }
            
            total_pages += pages
            total_errors += errors
        
        # Save enhanced statistics
        elapsed_time = time.time() - self.start_time
        repos_per_second = self.repo_count / elapsed_time if elapsed_time > 0 else 0
        
        with open('crawler_stats.txt', 'w') as f:
            f.write(f"Crawler Statistics:\n")
            f.write(f"Total runtime: {elapsed_time:.1f} seconds\n")
            f.write(f"Repositories collected: {self.repo_count}\n")
            f.write(f"Total pages processed: {total_pages}\n")
            f.write(f"Total errors: {total_errors}\n")
            f.write(f"Average speed: {repos_per_second:.1f} repos/second\n")
            f.write(f"Number of workers: {len(worker_metrics)}\n\n")
            
            f.write("Worker Statistics (sorted by repos processed):\n")
            sorted_workers = sorted(worker_metrics.items(), key=lambda x: x[1]['repos'], reverse=True)
            
            for worker_id, metrics in sorted_workers:
                f.write(f"Worker {worker_id % 1000}:"
                       f" Pages={metrics['pages']}"
                       f" Repos={metrics['repos']}"
                       f" Avg={metrics['avg_repos_per_page']:.1f} repos/page"
                       f" Errors={metrics['errors']}\n") 